### ISSUE TITLE
I take issue with this

### ISSUE THREAD

**Issue by ryandonsullivan** [wpsitecare/example-plugin#2]
![u-mad](https://cloud.githubusercontent.com/assets/1830861/8442405/19dcc0fc-1f3c-11e5-9083-210b8efcf4a3.gif)

**Comment by robneu** [comment]
![giphy](https://cloud.githubusercontent.com/assets/2184093/8442484/de2a4fd0-1f44-11e5-919d-015dce76c904.gif)
