### ISSUE TITLE
Renamed Files Not Removed

### ISSUE THREAD

**Issue by robneu** [wpsitecare/example-plugin#3]
When the `grunt newplugin` command is run, all references to the old plugin are renamed and a few files are copied with new names. This works fine, but the original files aren't removed.

The best way to handle this would be through `grunt-contrib-clean` but I can't really think of a clean way to do it without pulling the config for the `clean` command into the plugin and also complicating the main `clean` alias that's run at the start of every build.

For now, it's simple enough to just delete the extra files manually but at some point i'd like to figure out a way to automate this.

**Comment by ctalkington** [comment]
just some feedback on how i do naming with similar flow:

i have `js/src/plugin.js` which is never renamed but i have the generated concat files named to be the `js/examplePlugin.pkgd.js` which is referenced in scripts factory same as you currently do but when it comes to loading unpacked.i just use `js/src/plugin{$suffix}.js` as i figured these are custom cases and when you view source you already have plugin path in front of it so I don't see much value in dealing with renaming that main source file.

**Comment by robneu** [comment]
Well, that takes care of everything but the root plugin file which is simple enough to just manually delete. Thanks @ctalkington!
